### ISSUE TITLE
parsing error in dwxml.py

### ISSUE THREAD

**Issue by SpandanKumarSahu** [TheGrayFrost/smartKT#3]
* To know more on the error, run the parser on projects/smallproj
* Missing handler for some `attr`

**Comment by SpandanKumarSahu** [comment]
@sumeetshirgure could you please solve this? Most times if the combine.py fails, it is mainly because of this issue which makes the XML incorrect.

**Comment by sumeetshirgure** [comment]
ddx.py is failing because of invalid tag generation issue in ast2xml, which should be fixed inside the sanitizer function parsers/ast2xml.cc:19
The missing DW_AT_ tag names have nothing to do with it, as they are not used by it. That's why I just emitted a warning in such cases. But I can still fix it as the upstream repository seems to have added those missing DWARF5 tag names.

**Comment by TheGrayFrost** [comment]
@sumeetshirgure camelCase didn't fix the ddx.py parse error... For some reason '(' and ')', which are valid xml characters still give parse error... I have added minor code to address that in commit 74ade152e67b4ab2c9b2e291942411e0a96207cd 
also, updating pyelftools didn't completely stop the warnings generated by dwxml... eg: try ./initialize.py testsuite/simple/

Closing since these are still minor issues.
